name: Compile

on:
  pull_request:
    branches: ["master"]
  workflow_dispatch:
env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    # if: "contains(github.event.head_commit.message, '[yes]')"
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Unwrap/Expect used
        run: |
          cargo clippy -- \
          -W clippy::unwrap_used \
          -W clippy::expect_used
      - name: Build
        run: cargo build
      - name: Run tests
        run: cargo test
